# Generated by Django 3.0.8 on 2020-07-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lazy_geo", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Correction",),
    ]
