[tool.poetry]
name = "tx_mixed_beverages"
version = "0.0.0"
description = "Texas Mixed Beverage Gross Receipts Tax data"
authors = []
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
