# Generated by Django 3.1 on 2020-08-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="data",
            field=models.JSONField(
                blank=True,
                help_text="denormalized data to help generate map data",
                null=True,
            ),
        ),
    ]
