# Generated by Django 4.0.2 on 2022-02-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_auto_20200809_0329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="coordinate_quality",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="1 is most accuracy, 0.8 is pretty close, anything less than 0.6 is bad",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
