# Generated by Django 5.2.11 on 2026-02-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_location_coordinate_quality_alter_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='tax_number',
            field=models.CharField(db_index=True, max_length=80, verbose_name='taxpayer number'),
        ),
    ]
