name: tx_mixed_beverages

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Black check
        run: pip install black
        run: black --check .
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Eslint check
        run: |
          npm install eslint
          npm run lint
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgis/postgis:12-3.0-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: sudo apt-get install -y libpq-dev libgeos-dev gdal-bin
      - run: |
          pip install poetry
          poetry install -v
        env:
          POETRY_VIRTUALENVS_IN_PROJECT: true
      - run: make test
        env:
          DATABASE_URL: postgis://postgres:postgres@127.0.0.1/github_actions
