name: tx_mixed_beverages

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  lint-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # https://github.com/astral-sh/setup-uv/releases
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - run: uv sync --all-extras
      - run: make lint
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "npm"
      - run: npm install
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: imresamu/postgis:16-3.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v6
      # https://github.com/astral-sh/setup-uv/releases
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - run: sudo apt-get install -y libpq-dev libgeos-dev gdal-bin
      - run: uv sync --all-extras
      - run: make test
        env:
          DATABASE_URL: postgis://postgres:postgres@127.0.0.1/github_actions
